### ISSUE TITLE
Issue with CentOS 7

### ISSUE THREAD

**Issue by bellwood** [dkoston/IpManager#6]
When changing an IP on a CentOS 7 based server named does not restart, it crashes.

After changing the IP we see in /var/log/messages when the following error the following routines are called in the plugin:

```
#Replace IP in DNS Zone
run_forked("sed -i 's/$old_ip/$new_ip/g' /var/named/$domain.db && /scripts/dnscluster synczone $domain");

#Reload DNS Zones
run_forked('/scripts/restartsrv_bind');
```
named[18207]: /etc/named.conf:1: open: /etc/rndc.key: permission denied

This file is confirmed to be properly chowned to named:named.

There also appears to be some inconsistencies with the Apache configuration being updated.

This issue persists across every CentOS 7 server we have with cPanel - CentOS 5 and CentOS 6 do not exhibit this issue.

A ticket with cPanel has yielded the above findings and it is their recommendation to disable the plugin which we'd prefer not to do as it is s valuable tool for the customer.

**Comment by kostonconsulting** [comment]
Sorry for the delayed response, I shut down the email associated with this account. 

Just tried on CENTOS 7.2 x86_64  WHM 54.0 (build 8) and didn't see this issue.

What does the following yield? `ls -la /etc/rndc.key`

**Comment by bellwood** [comment]
```
webserver: -rw-rw---- 1 named named 77 Nov  4 00:39 /etc/rndc.key
```

This was cPanel's response to us at the time:
```
I looked at the server logs to see if something else was happening at the same time as the most recent failure, and I may have found a correlation. I started looking at the logs based on the following event where named was restarted but then it did not have permission to read /etc/rndc.key so it failed to start:

Dec 11 09:53:51 webserver named[4058]: shutting down
... restarted ...
Dec 11 09:53:53 webserver named[18207]: /etc/named.conf:1: open: /etc/rndc.key: permission denied

I compared these events to /usr/local/cpanel/logs/access_log to see if someone had triggered an action to happen at that time, and found this (these logs use UTC timestamps, so are 5 hours offset from the server time):

X.X.X.X - XXXXXX [12/11/2015:14:53:43 -0000] "POST /cpsess1528583166/cgi/addons/ipmanager/index.cgi?action=selectip&hostname=XXXXXX.com&domain=XXXXXX&user=XXXXXX HTTP/1.1" 200 0 "https://webserver.com:2087/cpsess1528583166/cgi/addons/ipmanager/index.cgi?action=selectip&hostname=XXXXXX.com&domain=XXXXXX&user=XXXXXX" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0" "-" "-"
127.0.0.1 - root [12/11/2015:14:53:50 -0000] "POST /json-api/cpanel HTTP/1.1" 200 0 "" "Cpanel::PublicAPI (perl) 1.1" "a" "-"
127.0.0.1 - root [12/11/2015:14:53:50 -0000] "POST /json-api/cpanel HTTP/1.1" 200 0 "" "Cpanel::PublicAPI (perl) 1.1" "a" "-"

The "XXXXXX" user used the "IP Manager" plugin to change something. Looking at the code for /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi, I see that it does make some changes and actions that involve named in different parts of the script:

#Replace IP in DNS Zone
run_forked("sed -i 's/$old_ip/$new_ip/g' /var/named/$domain.db && /scripts/dnscluster synczone $domain");

#Reload DNS Zones
run_forked('/scripts/restartsrv_bind');

I do not know exactly how it comes about, but it may be possible that this script is causing a race-condition or some other type of issue which causes /etc/rndc.key to be inaccessible to named when it is restarted by this plugin.

Can you please try temporarily suspending the usage of this third-party plugin to see if that stops the "/etc/rndc.key: permission denied" errors during the named restarts that are seen in /var/log/messages?
```

Removing the plugin and then manually changing the IP for the customer works but its a tremendous amount of support overhead.

Thank you =)

**Comment by bellwood** [comment]
I've pushed 1.8 to the server referenced above and will report any additional issues - insight is still appreciated.

Thank you for your time and efforts =)

**Comment by kostonconsulting** [comment]
Understand the level of inconvenience. That's pretty odd as I'm never touching /etc/rndc.key directly and your permissions look correct. 

`/scripts/restartsrv_bind` is the script which is restarting named but that's distributed by cPanel and should just be restarting bind.

`/scripts/dnscluster synczone $domain` only does something if you have dns clustering enabled. You may want to try running it with $domain as the user's domain and see if the permissions on /etc/rndc.key get modified. I don't have dns clustering set up on my testing boxes at the moment but can try setting that up tonight.

`sed -i 's/$old_ip/$new_ip/g' /var/named/$domain.db`doesn't touch /etc/rndc.key, it's just replacing the IP address in the domain's dns record file.

Will give this another look tonight to see if I can reproduce the issue.

**Comment by bellwood** [comment]
We aren't using clustering either on these servers so that is likely a non-issue.

Completely agree on the named service restart - that part works, it reloads the daemon but with rndc.key not being accessible it fails to reload completely.

I would back burner this for the moment in lieu of #7 as testing this issue won't really be possible unless the plugin itself is functioning.

Thanks again for the help =)

**Comment by dkoston** [comment]
I added a new feature to call /scripts/fixrndc before restarting the dns server in version 2.1. This should hopefully fix up any permissions issues and prevent this error. I'm not able to cause the error on my server so if you can test, that'd be great.
