### ISSUE TITLE
Issue with WHM 54

### ISSUE THREAD

**Issue by samuelado** [dkoston/IpManager#7]
Ip Manager plugin doesn't work with WHM 54 (CentOS 6.x and CentOS 7.x)

cPanel support says "The update to cPanel 54 changes core paths used by plugins, so the author may just need to update the plugin to use the correct paths"

Any luck to have a look into issue ?

Thx

**Comment by kostonconsulting** [comment]
Sorry, shut down the consulting email and hadn't seen these issues. Taking a look at their docs now to see what updates are needed.

**Comment by kostonconsulting** [comment]
Had to boot up some new VPSes w/ CentOS 6 and 7. Getting an issue connecting to the WHM API which is killing my process. Turning on debug mode in Cpanel::PublicAPI doesn't give any useful info. Will be looking into the strace details to see if I can find anything.

> Could not connect to 127.0.0.1:2087:  at /usr/local/cpanel/3rdparty/perl/514/lib64/perl5/cpanel_lib/cPanel/PublicAPI.pm line 205.
[2016-02-02 21:57:33 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2d23cb0)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2d23cb0), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x2fd35b0), __CPANEL_HIDDEN__, GLOB(0x2fd3b98)) called at cpsrvd.pl line 6228
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5722
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1641
	cpanel::cpsrvd::dodoc(HASH(0x17eb560)) called at cpsrvd.pl line 1324
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
	cpanel::cpsrvd::script() called at cpsrvd.pl line 339

**Comment by kostonconsulting** [comment]
Ok, I believe the issue is that Cpanel::PublicAPI is using IO::Socket::SSL to connect to WHM's API but it's not configured properly to use the self-signed WHM cert. Getting this error back from IO::Socket::SSL->new():

IO::Socket::INET configuration failed SSL connect attempt failed with unknown error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by kostonconsulting** [comment]
Ok, give it a shot now. Things are working fine for me on CENTOS 7.2 x86_64 WHM 54.0 (build 8)

**Comment by samuelado** [comment]
Hello,

Thanks for your kind help.
v1.8 is working fine with root level but it gives blank page and following error for reseller level user ;

Server Error from 127.0.0.1: HTTP/1.1 403 Forbidden Access denied
[2016-02-03 07:08:04 +0000] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN45> line 22.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x33bd228)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x33bd228), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x33bcf88), __CPANEL_HIDDEN__, GLOB(0x33bcfa0)) called at cpsrvd.pl line 6228
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5722
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1641
	cpanel::cpsrvd::dodoc(HASH(0x17f5c78)) called at cpsrvd.pl line 1324
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
	cpanel::cpsrvd::script() called at cpsrvd.pl line 339

is it related to WHM settings ?

Thanks

**Comment by samuelado** [comment]
Sorry forgot to mention...
It was CentOS 6.7 x86_64

**Comment by samuelado** [comment]
Just tested with fresh installated CentOS 7.2 x86_64 WHM 54.0 (build 8)
root level is fine
reseller level giving blank page and following error ;

Server Error from 127.0.0.1: HTTP/1.1 403 Forbidden Access denied
[2016-02-03 07:55:52 +0000] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN21> line 6.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2777a70)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2777a70), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x2777ef0), __CPANEL_HIDDEN__, GLOB(0x2782cc8)) called at cpsrvd.pl line 6228
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5722
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1641
	cpanel::cpsrvd::dodoc(HASH(0x17eb560)) called at cpsrvd.pl line 1324
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
	cpanel::cpsrvd::script() called at cpsrvd.pl line 339

**Comment by kostonconsulting** [comment]
Yes, I've verified that resellers aren't working. I'm using the resellers access hash $HOME/.accesshash to conenct to the WHM API. In previous versions of cPanel/WHM, I could call this to generate the hash if it didn't exist: `/usr/local/cpanel/whostmgr/bin/whostmgr setrhash'`. That is no longer working for resellers or requires a setting to be toggled. Unfortunately, there seems to be multiple problems as navigating to "Remote Access Key" in WHM will create the reseller's access hash but I'm still getting the 403 back from the API.

Will have to add some more debugging code tonight to sort this one out. Sorry for the delay.

**Comment by bellwood** [comment]
I can confirm the same issue when logged in as root and user on CentOS 6 and 7 running WHM 54

```
[2016-02-03 10:12:13 -0500] warn [index] API Error 1 - gather_list_of_accounts() -  at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 260.
	main::gather_list_of_accounts() called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 72
Use of uninitialized value in string eq at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 252.
Use of uninitialized value in concatenation (.) or string at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 260.
[2016-02-03 10:17:50 -0500] warn [index] API Error 1 - gather_list_of_accounts() -  at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 260.
	main::gather_list_of_accounts() called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 72
[2016-02-03 10:37:49 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN5817> line 12.
[2016-02-03 10:38:09 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN5826> line 6.
[2016-02-03 10:38:18 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN5826> line 8.
	Cpanel::Config::LoadCpUserFile::loadcpuserfile("") called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 85
	Cpanel::Config::LoadCpUserFile::loadcpuserfile("") called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 85
Use of uninitialized value in numeric eq (==) at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 285.
Can't locate object method "error" via package "Cpanel::Logger" at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 290.
[2016-02-03 10:43:34 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
```

**Comment by kostonconsulting** [comment]
Ok, this appears to be related to some permissions within the whostmgrd web server. I'm able to get the list of accounts fine when executing via shell as a reseller user:

`# ./test.cgi 
Accounts: $VAR1 = {
          'status' => 1,
          'accounts' => [
                          {
                            'maxaddons' => '*unknown*',
                            'ip' => '192.168.1.2',
                            'diskused' => 'none',
                            'legacy_backup' => 0,`

Investigating their plugin ACL setup as that may have been locked down in newer versions of WHM

**Comment by kostonconsulting** [comment]
Found it. Looks like $ENV{'HOME'} changed behavior in WHM when emulating root. Added a fix using getpwnam() to ensure it's always correct. Please try installing 1.9 and let me know if you still see any issues. Sorry for missing the reseller side.

**Comment by samuelado** [comment]
Thanks a lot for your time and efforts....
root is good and working fine but reseller is still giving blank page.

Centos 6.7 x86_64 WHM 54.0 (build 8)
----------------------------------------------------
[2016-02-03 22:28:19 -0500] die [index] Cannot open access hash: /home/mydomain/.accesshash at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 480.
	main::load_accesshash() called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 234
	main::gather_list_of_accounts() called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 71
exit level [die] [pid=36562] (Cannot open access hash: /home/mydomain/.accesshash)
[2016-02-03 22:28:19 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN34> line 18.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x288bf08)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x288bf08), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x29622e0), __CPANEL_HIDDEN__, GLOB(0x28899e8)) called at cpsrvd.pl line 6228
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5722
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1641
	cpanel::cpsrvd::dodoc(HASH(0x17f5c78)) called at cpsrvd.pl line 1324
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
	cpanel::cpsrvd::script() called at cpsrvd.pl line 339

+++++++++++++++++

Centos 7.2 x86_64 WHM 54.0 (build 8)
----------------------------------------------------
[2016-02-04 03:27:29 +0000] die [index] Cannot open access hash: /home/mydomain/.accesshash at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 480.
	main::load_accesshash() called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 234
	main::gather_list_of_accounts() called at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 71
exit level [die] [pid=9336] (Cannot open access hash: /home/mydomain/.accesshash)
[2016-02-04 03:27:29 +0000] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155, <GEN19> line 46.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2c22a18)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2c22a18), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x2c2e568), __CPANEL_HIDDEN__, GLOB(0x2c2e448)) called at cpsrvd.pl line 6228
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5722
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1641
	cpanel::cpsrvd::dodoc(HASH(0x17eb560)) called at cpsrvd.pl line 1324
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
	cpanel::cpsrvd::script() called at cpsrvd.pl line 339

just wondering if we miss something if it worked for you..

Thx again.

**Comment by kostonconsulting** [comment]
Looks like it's still not generating the accesshash if you don't already have one set. Sorry, forgot that was the case. You'll need to navigate to "Remote Access Key" in WHM as the reseller before you can use the plugin for a short-term fix until I can figure out a permanent fix for that.

**Comment by kostonconsulting** [comment]
There's definitely a lot that has changed over the last 2 years since I've looked at this plugin. Just pushed a 2.0 fix up which should cover the issue.

**Comment by samuelado** [comment]
:-)
Seems issue fixed for Centos 6.7 and CentOS 7.2 with WHM 54.0 (build 8)
We appreciate your help.
We will try with DNS Cluster and will report..

Thanks again..

**Comment by samuelado** [comment]
Had a detailed look.
CentOS 7.2 x86_64
--------------------------
v2.0 changes the ip address, list accounts shows the account with new ip, httpd.conf is fine with new ip but DNS zone file with related domain remains with old ip.
Thx

**Comment by dkoston** [comment]
Interesting. @samuelado are you seeing that /var/named/$domain.$tld.db isn't updated or that the DNS record returns the old IP address? 

I'm seeing /var/named/$domain.$tld.db updated on CENTOS 7.2 x86_64. However, cPanel sets the DNS records TTL at 14400 seconds (4 hours) by default so it will take a while before resolvers start picking up the new IP address.

**Comment by samuelado** [comment]
Hey Dave,

/var/named/$domain.$tld.db isn't updated.. logs as attached
[centos7-named-logs.txt](https://github.com/dkoston/IpManager/files/117615/centos7-named-logs.txt)

more than 4 hours and nothing changed :-(
====
DNS Cluster (Centos 6.x servers)
I tried v2.0 in a server which is in dns cluster and same thing happened... dns zone isn't updated with new ip and almost same error logs

Thanks

**Comment by bellwood** [comment]
@dkoston any update? Thank you =)

**Comment by dkoston** [comment]
I'm not able to replicate the dns edit issue on my side. I'll try to add a bunch of debug code tonight so that we can see if there are any errors captured.

I also vaguely remember a script that cPanel has which fixes the ends.key permissions issue so I'll add some code to execute that script before trying to restart the DNS server

**Comment by bellwood** [comment]
In this case the issue remaining is when you are in WHM as the reseller and try to load the plugin you get a blank white screen:

```
Can't use an undefined value as an ARRAY reference at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 252.
[2016-02-08 13:55:49 -0500] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x390e388)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x390e388), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x3993418), __CPANEL_HIDDEN__, GLOB(0x39b6af8)) called at cpsrvd.pl line 6245
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5739
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1641
	cpanel::cpsrvd::dodoc(HASH(0x17f1cd8)) called at cpsrvd.pl line 1324
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
	cpanel::cpsrvd::script() called at cpsrvd.pl line 339
```

**Comment by dkoston** [comment]
Looks like that reseller may not have access to list any accounts. I added an additional check to make sure their account list is populated in a new version 2.1. Also added information to the README about how to turn on a new debug mode which shows the output of cPanel/WHM api calls in /usr/local/cpanel/logs/error_log in case that fix didn't work for you

**Comment by bellwood** [comment]
So in testing, I have a user in WHM that has list accounts and reseller privs

Debug:
```
[2016-02-09 08:18:08 -0500] info [index] API Response - WHM::listaccts:
{
   "data" : {},
   "metadata" : {
      "version" : 1,
      "reason" : "OK",
      "command" : "listaccts",
      "result" : 1
   }
}
```

The ACL associated to my resellers:
```
[~]# cat /var/cpanel/acllists/reseller
add-pkg=1
add-pkg-ip=1
add-pkg-shell=0
all=0
allow-addoncreate=1
allow-emaillimits-pkgs=0
allow-parkedcreate=1
allow-unlimited-bw-pkgs=1
allow-unlimited-disk-pkgs=1
allow-unlimited-pkgs=1
clustering=0
create-acct=1
create-dns=1
demo=0
demo-setup=1
disallow-shell=1
edit-account=0
edit-dns=1
edit-mx=1
edit-pkg=1
frontpage=1
kill-acct=1
kill-dns=1
limit-bandwidth=0
list-accts=1
locale-edit=0
mailcheck=1
news=1
park-dns=1
passwd=1
quota=0
rearrange-accts=0
res-cart=0
resftp=0
restart=0
show-bandwidth=1
software-attracta=1
ssl=1
ssl-buy=0
ssl-gencrt=1
stats=0
status=0
suspend-acct=1
thirdparty=0
upgrade-account=1
viewglobalpackages=1
```

**Comment by dkoston** [comment]
Make sure that the reseller has 'list-accts' here as well:

`# cat /var/cpanel/resellers`
`newdomain:add-pkg,create-acct,create-dns,disallow-shell,edit-dns,edit-mx,edit-pkg,kill-acct,kill-dns,list-accts,mailcheck,news,park-dns,passwd,show-bandwidth,ssl,ssl-buy,ssl-gencrt,suspend-acct,thirdparty,upgrade-account,viewglobalpackages`

I'm not able to reproduce an issue where a reseller is unable to list the accounts that they own. You can try the following to see if it addresses your issue:

comment out lines 214-244 of /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi like so:

`#    unless ( $ENV{'REMOTE_USER'} eq 'root' ) {`

`#        $api_params->{searchtype} = 'owner';`

`#        $api_params->{search}     = $ENV{'REMOTE_USER'};`

`#    }`

**Comment by luuvuong** [comment]
malformed UTF-8 character in JSON string, at character offset 4508 (before "\x{e9802}","shell":"...") at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 248.
[2016-02-24 13:38:29 +0700] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
        Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x3ab6720)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
        Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x3ab6720), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x3ab6498), __CPANEL_HIDDEN__, GLOB(0x3ab64b0)) called at cpsrvd.pl line 6253
        cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5747
        cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1645
        cpanel::cpsrvd::dodoc(HASH(0x1802ea0)) called at cpsrvd.pl line 1281
        cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
        cpanel::cpsrvd::script() called at cpsrvd.pl line 339


When i login by root. I access plugin, it is show page page and error_log into /usr/local/cpanel/logs/error_log

**Comment by dkoston** [comment]
@luuvuong this is due to an invalid UTF-8 character listed as part of the account's information. You can find out what part of the account information has this character using the 'Debugging' section here: https://github.com/dkoston/IpManager/blob/master/README.md

Then, I'd recommend removing the invalid UTF-8 character from the account's information.

If it's part of an IDN or you don't believe the information to be invalid, feel free to send over the output in the logs via direct message on twitter as it will have account info in it. My handle is @davekoston

**Comment by luuvuong** [comment]
@davekoston, i use "debuggin" https://github.com/dkoston/IpManager/blob/master/README.md but i no see debug with error_log
[2016-02-24 13:38:29 +0700] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
Cpanel::Server::Handlers::SubProcess::report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x3ab6720)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x3ab6720), __CPANEL_HIDDEN_, CPANEL_HIDDEN..., CPANEL_HIDDEN, IO::Handle=GLOB(0x3ab6498), CPANEL_HIDDEN, GLOB(0x3ab64b0)) called at cpsrvd.pl line 6253
cpanel::cpsrvd::cgiHandler(CPANEL_HIDDEN, CPANEL_HIDDEN, CPANEL_HIDDEN, CPANEL_HIDDEN) called at cpsrvd.pl line 5747
cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1645
cpanel::cpsrvd::dodoc(HASH(0x1802ea0)) called at cpsrvd.pl line 1281
cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 844
cpanel::cpsrvd::script() called at cpsrvd.pl line 339

This is image my error on Cpanel when login with root http://host3.vuonglv.name.vn/error_ip_manager.png

**Comment by dkoston** [comment]
@luuvuong let me know if you're still getting this issue after updating to version 2.2 of IpManager
