### ISSUE TITLE
WHM 56 will use Perl 5.22

### ISSUE THREAD

**Issue by bellwood** [dkoston/IpManager#9]
cPanel is updating from Perl 5.14.4 to 5.22.

They are warning plugin vendors:

https://blog.cpanel.com/were-moving-to-perl-5-22-in-cpanel-whm-version-56/

Just an FYI

**Comment by dkoston** [comment]
Thanks for the heads up. I'll see if I can get some tests run this weekend to ensure compatibility

**Comment by phuong-nt** [comment]
Hello, 

I have update Cpanel to version 56, plugn IP Manager don't work, it's show error.
Could you please tell me how to fix it.

Regards.


CGI::param called in list context from /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 61, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/CGI.pm line 404.
CGI::param called in list context from /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 62, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/CGI.pm line 404.
CGI::param called in list context from /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 63, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/CGI.pm line 404.
CGI::param called in list context from /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 64, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/CGI.pm line 404.
CGI::param called in list context from /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 65, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/cpanel/3rdparty/perl/522/lib64/perl5/cpanel_lib/CGI.pm line 404.
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 248.
[2016-04-28 14:29:12 +0700] warn [cpsrvd] The subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi) exited with an error: The subprocess reported error number 255 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 155.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0xe9f598)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 72
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0xe9f598), __CPANEL_HIDDEN__, __CPANEL_HIDDEN__..., __CPANEL_HIDDEN__, IO::Handle=GLOB(0x4041df8), __CPANEL_HIDDEN__, GLOB(0x405c8f0)) called at cpsrvd.pl line 6308
	cpanel::cpsrvd::cgiHandler(__CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__, __CPANEL_HIDDEN__) called at cpsrvd.pl line 5792
	cpanel::cpsrvd::dodoc_whostmgrd() called at cpsrvd.pl line 1674
	cpanel::cpsrvd::dodoc(HASH(0xeda110)) called at cpsrvd.pl line 1347
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 841
	cpanel::cpsrvd::script() called at cpsrvd.pl line 334

**Comment by dkoston** [comment]
Interesting. It looks like the JSON coming back from the cPanel API is not valid. Perhaps it's an authentication issue:

"malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/local/cpanel/whostmgr/docroot/cgi/addons/ipmanager/index.cgi line 248."

I'll try to reproduce this as soon as I can get access to a cPanel server to test on.

**Comment by bellwood** [comment]
@dkoston I can provide access to a cPanel VPS if that helps - just let me know how to reach out outside of Github to provide the details.

**Comment by dkoston** [comment]
Thanks @bellwood, got a chance to look now and this has been fixed in version 2.2
